- svgs/file-gif_E833.svg
Adds gif icon to be used in mobile app to indicate gif images (since they don't play automatically until viewed in the gallery).
> add gif icon

- svgs/lightning-bolt-outline_F140C.svg
This is the icon needed for the button to open the run actions modal.
I've always wanted to try and add an icon here :nerd_face: I hope I did it right!
> Add lightning-bolt-outline icon

- generate-data.js
adds `title` attribute to SVG and changes the default value for the `fill` attribute to `currentColor`
> [MM-46602]: adds title attribute to svg

- svgs/code-block_ E835.svg
Adds a new code block icon to be used for the WYSIWYG editor
> add code block icon

- svgs/code-block_ E835.svg
Small tweak to adjust positioning of the code brackets in the icon
> Update to code block icon

- svgs/shuffle-variant_F049F.svg
Adds a new 'shuffle' icon to the icon set. To be used in boards for 'random' emoji pick
> Add shuffle icon

- package-lock.json
- package.json
A PR to bump the version to 0.1.28 for new release
> Bump version to v0.1.28 for release

- sort-ascending_F04BC.svg
Adds a new icon to be used in the playbooks RHS in channels to sort runs
> Add sort icon for runs RHS

- README.md
Updates the readme file to include a code snippet for SVGs
> Update Readme file to include SVG code template

- svgs/keyboard-return_F0311.svg
Adds keyboard return icon for use in link popover for WYSIWYG editor
> adds keyboard return icon

- package-lock.json
- package.json
Updating version number to prep for new release
> version bump to 0.1.36

- svgs/headphones_F02CB.svg
This PR adds the headphone icon svg
> Adds headphones icon

- package-lock.json
- package.json
updated the version number for a new release
> version bump to 0.1.38

- package-lock.json
- package.json
Updated version number for next release
> Version bump v0.1.39

- package-lock.json
- package.json
> version bump 0.1.40

- package-lock.json
- package.json
- svgs/video-off-outline_F0BDB.svg
- svgs/video-outline_F0BDC.svg
Updating the current video icon and adding a new video-off icon
Also bumping version number for release
> Adding video icons and bumping version

- svgs/icon-brand-giphy_E838.svg
Adds the giphy icon - used in the gif picker tab
> add giphy icon

- package-lock.json
- package.json
- svgs/creation-outline_F1C2B.svg
Adds the sparkle icon for AI purposes and updates the version number to be released
> Sparkle icon and version bump

- package-lock.json
- package.json
Added the map marker icon, bumping the version for a release
> version bump to 0.1.45

- svgs/upload-outline_F0E07.svg
Addes the upload icon to the repo
> Add upload icon

- package-lock.json
- package.json
Bumps version number to 0.1.46
> 0.1.46 version bump

- package-lock.json
- package.json
> 0.1.47 version bump

- .github/workflows/compass-icons.yml
- .github/workflows/publish.yml
Seems like there are deprecated actions, this PR intends to update them.
> Update ci action checkout

- README.md
- package-lock.json
- package.json
> Version Bump to 0.1.49
